---
- name: Install package dependencies
  package:
    name: >
      {{
        (mutt_packages|length > 0) |
        ternary(
          mutt_packages,
          (
            lookup(
              'vars',
              'mutt_packages_'+ansible_distribution|lower+ansible_distribution_major_version|string,
              default=''
            ) |
            ternary(
              lookup(
                'vars',
                'mutt_packages_'+ansible_distribution|lower+ansible_distribution_major_version|string,
                default=''
              ),
              lookup(
                'vars',
                'mutt_packages_'+ansible_distribution|lower
              )
            )
          )
        )
      }}
    state: present
